name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Or your default branch if not 'main'
  workflow_dispatch: # Allows manual triggering

# Permissions needed for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

#Concurrency ensures that only one deployment runs at a time for this group
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify your Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Use 'ci' for cleaner installs in CI environments

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3 # Or a newer version like @v4 or @v5 if preferred

      - name: Build Next.js site
        run: npm run build # This command should trigger 'next build' which handles static export
                          # Ensure your next.config.js has `output: 'export'`

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2 # Using v2, v3 is also available
        with:
          # Path to the directory to upload (default for Next.js static export is 'out')
          path: './out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # Using v2, v4 is also available